   ###                   15- Numpy in python


---

- How to create an array

In [2]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

- check the type of array

In [3]:
type(a)

numpy.ndarray

- Add a list in list of arrays

In [5]:
#List of list in array
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 1D array

In [6]:
import numpy as np
a=np.array([5,5,5])   #This is 1-D array because it give only one row
a

array([5, 5, 5])

- check type of array

In [7]:
type(a)

numpy.ndarray

- check length of array

In [8]:
len(a)

3

- indexing in array

In [11]:
a[0] #it mean show first character in variable a

5

- indexing in array

In [12]:
a[0:]

array([5, 5, 5])

- use np.zeros function

In [20]:
b=np.zeros(2) # mean that 0 humy 2 dafa print kar do.
b

array([0., 0.])

- use .ones function

In [21]:
c=np.ones(3) #mean that print 1 in 3 times
c

array([1., 1., 1.])

- use .empty function

In [22]:
d=np.empty(3)
d

array([1., 1., 1.])

- use .arange function

In [23]:
e=np.arange(6)  #mean that hum 6 ka beach ke range ma sari values print kar do
e

array([0, 1, 2, 3, 4, 5])

In [24]:
f=np.arange(2,20) #mean k humy 2 or 20 ka beach ke sari values print kar do
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
g=np.arange(2,20,2) #mean ka hymy 2 or 20 ka beach ke sari values print kar do but 2 ka gap sa
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
h=np.linspace(0,10,num=5) #mean k humy 0 or 10 ka beach ma 5 values print kar do 
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
#specific data type in array
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [28]:
j=np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

---

### 2 D array

In [13]:
b=np.array([[5,5,5],[5,5,5],[5,5,5]]) #This is two dimensional array because it give one row and one coloumn. 
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- check type 

In [14]:
type(b)

numpy.ndarray

- check length

In [15]:
len(b)

3

- indexing in array

In [16]:
b[0]

array([5, 5, 5])

- indexing in array

In [17]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
#mean ka zero show karo 3 by 4 (3 mean 3 coloumn and 4 mean 4 row)
np.zeros((3,4)) 




array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#mean k 5 by 6 ke array show karo(5 mean 5 coloumn and 6 mean 6 row)
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
# 3 by 4 ke array show karo
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

---

### 3D array

In [38]:
#making and reshaping a 3d array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])