### 17- Arrays functions in numpy

---

- create an 1D array

In [2]:
import numpy as np

a=np.array([10,12,1,17,3,887,43,31,19,17,211])
a

array([ 10,  12,   1,  17,   3, 887,  43,  31,  19,  17, 211])

In [4]:
a.sort() #sort function are use to arange a number in asending order 
a

array([  1,   3,  10,  12,  17,  17,  19,  31,  43, 211, 887])

In [5]:
#create an another array
b=np.array([3,7,11,9,15,])
b

array([ 3,  7, 11,  9, 15])

In [7]:
#concatinatre an array of a & b
c=np.concatenate((a,b))
c

array([  1,   3,  10,  12,  17,  17,  19,  31,  43, 211, 887,   3,   7,
        11,   9,  15])

In [9]:
#sort the c array
c.sort()
c

array([  1,   3,   3,   7,   9,  10,  11,  12,  15,  17,  17,  19,  31,
        43, 211, 887])

---

- create a 2D array

In [10]:
#create an array
x=np.array([[1,2],[5,6]])
x

array([[1, 2],
       [5, 6]])

In [11]:
#create an another array
y=np.array([[6,7],[7,8]])
y

array([[6, 7],
       [7, 8]])

In [16]:
#concatinate a x and y array
np.concatenate((x,y))

array([[1, 2],
       [5, 6],
       [6, 7],
       [7, 8]])

In [17]:
#concatinate a array on axis 0
np.concatenate((x,y),axis=0)

array([[1, 2],
       [5, 6],
       [6, 7],
       [7, 8]])

In [18]:
#concatinate a array on axis 1
np.concatenate((x,y),axis=1)

array([[1, 2, 6, 7],
       [5, 6, 7, 8]])

In [23]:
#create a 3D array
a=np.array([[[0,1,2,3],[4,5,6,7]],
[[0,1,2,3],[4,5,6,7]],
[[0,1,2,3],[4,5,6,7]]])

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

- use .ndim function
   - ndim function use to check the dimension of arrays k arrays 1D hen yah 2D hen yah 3 d

In [24]:
a.ndim

3

In [27]:
#create 2D array
b=np.array([[5,6,7],[7,9,1,],[4,5,6,],])
b

array([[5, 6, 7],
       [7, 9, 1],
       [4, 5, 6]])

In [28]:
#check dimension of array
b.ndim

2

In [29]:
#check size of array how many numbers are present in array
a.size

24

In [30]:
#to check shape how many dimension how many rows and how many coloumn
a.shape

(3, 2, 4)

In [31]:
#range 
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
#reshape
a.reshape(3,3) #3*3=9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#convert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#for rows
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
#for coloumn 
b=a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#multiply a with 6
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [38]:
#add a with 6
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
#sum all the values of a
a.sum()

45

In [40]:
#mean of a variable
a.mean()

5.0